# Generated by Django 5.2.1 on 2025-05-17 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.PositiveSmallIntegerField(unique=True)),
                ('device_name', models.CharField(max_length=30, unique=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='phone_number',
            field=models.PositiveIntegerField(verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='temprorydata',
            name='gift_number',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد جایزه'),
        ),
        migrations.AlterField(
            model_name='temprorydata',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='device_number',
            field=models.ForeignKey(db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.device', to_field='device_id'),
        ),
    ]
