# Generated by Django 5.2.1 on 2025-05-17 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_device_alter_rowdata_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'دستگاه', 'verbose_name_plural': 'دستگاه'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصولات', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='rowdata',
            options={'verbose_name': 'داده های کلی', 'verbose_name_plural': 'داده های کلی'},
        ),
        migrations.AlterModelOptions(
            name='temprorydata',
            options={'verbose_name': 'داده های موقت', 'verbose_name_plural': 'داده های موقت'},
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='شناسه دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='device_number',
            field=models.ForeignKey(db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.device', to_field='device_id', verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='rowdata',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', to_field='product_id', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='temprorydata',
            name='phone_number',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='شماره تلفن'),
        ),
    ]
