# Generated by Django 5.2.1 on 2025-05-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_device_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rowdata',
            old_name='device_number',
            new_name='device_id',
        ),
    ]
