# Generated by Django 5.2.1 on 2025-05-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_device_number_rowdata_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='phone_number_device',
            field=models.PositiveBigIntegerField(null=True, verbose_name='شماره تلفن دستگاه'),
        ),
    ]
