# Generated by Django 5.2.1 on 2025-05-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_device_phone_number_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='phone_number_device',
            new_name='deviceـphone_number',
        ),
        migrations.AddField(
            model_name='device',
            name='deviceـactivity',
            field=models.BooleanField(null=True, verbose_name='وضعیت دستگاه'),
        ),
    ]
