# Generated by Django 5.2.1 on 2025-05-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_phone_number_device_device_deviceـphone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceـactivity',
            field=models.BooleanField(verbose_name='وضعیت دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceـphone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='شماره تلفن دستگاه'),
        ),
    ]
