# Generated by Django 5.2.1 on 2025-10-02 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_device_deviceـactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temprorydata',
            name='device_id',
            field=models.ForeignKey(db_column='device_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.device', to_field='device_id', verbose_name='دستگاه'),
        ),
        migrations.AddField(
            model_name='temprorydata',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product', to_field='product_id', verbose_name='محصول'),
        ),
    ]
