# Generated by Django 5.2.1 on 2025-10-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_temprorydata_device_id_temprorydata_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temprorydata',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='temprorydata',
            name='product_id',
        ),
    ]
