# Generated by Django 5.2.1 on 2025-10-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_temprorydata_device_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rowdata',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='rowdata',
            old_name='product_id',
            new_name='product',
        ),
    ]
