# Generated by Django 5.2.1 on 2025-10-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_device_id_rowdata_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rowdata',
            old_name='device',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='rowdata',
            old_name='product',
            new_name='product_id',
        ),
    ]
