# Generated by Django 5.2.1 on 2025-10-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_device_rowdata_device_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='گزارش')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='دستگاه')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارش\u200cها',
            },
        ),
    ]
