# Generated by Django 5.2.1 on 2025-10-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveBigIntegerField(unique=True, verbose_name='شماره تلفن (بدون صفر اول)')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شماره تلفن محافظت\u200cشده',
                'verbose_name_plural': 'شماره\u200cهای تلفن محافظت\u200cشده',
            },
        ),
    ]
