# Generated by Django 5.2.1 on 2025-11-10 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('home', '0015_protectedphonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.token', verbose_name='توکن'),
        ),
    ]
