# Generated by Django 5.2.1 on 2025-11-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_device_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceـactivity',
            new_name='device_activity',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='deviceـphone_number',
            new_name='device_phone_number',
        ),
    ]
