# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvFc3vFFulaHMUlnaz45XkbmPHPzyN4Q
"""

from django.db import models
from rest_framework.authtoken.models import Token


# Create your models here.


class Product(models.Model):
    product_id = models.PositiveSmallIntegerField(unique=True, verbose_name='شناسه محصول')
    product_name = models.CharField(max_length=30, unique=True, verbose_name='نام محصول')
    datetime_updated = models.DateTimeField(auto_now=True)
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "محصولات"
        verbose_name_plural = "محصولات"

    def __str__(self):
        return self.product_name or "Untitled"



class Device(models.Model):
    device_id = models.PositiveSmallIntegerField(unique=True, verbose_name='شناسه دستگاه')
    # device_name = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نام دستگاه')
    device_name = models.CharField(max_length=30, unique=True, verbose_name='نام دستگاه')
    # device_name_per = models.CharField(max_length=30, unique=True, verbose_name='نام فارسی دستگاه')
    device_phone_number = models.PositiveBigIntegerField(null=True, blank=True, verbose_name='شماره تلفن دستگاه')
    device_token = models.OneToOneField(Token, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='توکن')
    device_activity = models.BooleanField(verbose_name='وضعیت دستگاه')
    datetime_updated = models.DateTimeField(auto_now=True)
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "دستگاه"
        verbose_name_plural = "دستگاه"

    def __str__(self):
        return self.device_name or "Untitled"

    @property
    def display_name(self):
        """نمایش FirstName LastName برای Admin"""
        if self.device_token and self.device_token.user:
            return f"{self.device_token.user.first_name}"
        return self.device_name
    display_name.fget.short_description = "نام دستگاه"
    

class RowData(models.Model):
    phone_number = models.PositiveBigIntegerField(verbose_name='شماره تلفن') # example 09904574830 ----> 904574830
    device_id = models.ForeignKey(Device, on_delete=models.SET_NULL, null=True, to_field='device_id', db_column='device_id', verbose_name='نام دستگاه')
    product_id = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, to_field='product_id', db_column='product_id', verbose_name='نام محصول')
    datetime_updated = models.DateTimeField(auto_now=True)
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "داده های کلی"
        verbose_name_plural = "داده های کلی"

    def __str__(self):
        return ('0' + str(self.phone_number)) or "Untitled"
    

class TemproryData(models.Model):
    phone_number = models.PositiveBigIntegerField(unique=True, verbose_name='شماره تلفن')
    gift_number = models.PositiveSmallIntegerField(verbose_name='تعداد جایزه')
    datetime_updated = models.DateTimeField(auto_now=True)
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "داده های موقت"
        verbose_name_plural = "داده های موقت"

    def __str__(self):
        return ('0' + str(self.phone_number)) or "Untitled"


class Report(models.Model):
    report = models.TextField(verbose_name='گزارش')
    device_id = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        verbose_name='دستگاه'
    )
    datetime = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')

    class Meta:
        verbose_name = "گزارش"
        verbose_name_plural = "گزارش‌ها"

    def __str__(self):
        return f"گزارش {self.device_id}"



class ProtectedPhoneNumber(models.Model):
    phone_number = models.PositiveBigIntegerField(
        unique=True,
        verbose_name='شماره تلفن (بدون صفر اول)'
    )
    datetime_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "شماره تلفن محافظت‌شده"
        verbose_name_plural = "شماره‌های تلفن محافظت‌شده"

    def __str__(self):
        return '0' + str(self.phone_number)

