# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M4yPG2hgC3RClmIRQOBVPseJU1EJPgm
"""

from home.models import RowData, TemproryData, Report
from rest_framework import serializers


class RowDataSerializer(serializers.ModelSerializer):
    class Meta:
        model = RowData
        fields = ('phone_number', 'device_id', 'product_id')

class TemproryDataSerializer(serializers.ModelSerializer):
    class Meta:
        model = TemproryData
        fields = ('phone_number', 'gift_number')


class ReportSerializer(serializers.ModelSerializer):
    class Meta:
        model = Report
        fields = ['report', 'device_id', 'datetime']

