# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M4yPG2hgC3RClmIRQOBVPseJU1EJPgm
"""

from django.urls import path
from home import views


app_name='home'

urlpatterns = [
    # path('home/', include('home.urls'), name='home')
    # path('post/', views.PostMetadataView.as_view(), name='post'),
    # path('device/', views.DeviceActivity.as_view(), name='device'),
    # path('report/', views.report_api, name='report-api'),

    path('get/', views.GetMetadataView.as_view(), name='get'),
    path('post/', views.PostMetadataView.as_view(), name='post'),
    path('re/', views.ReportMetadataView.as_view(), name='report'),
]

