# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvFc3vFFulaHMUlnaz45XkbmPHPzyN4Q
"""

# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19M4yPG2hgC3RClmIRQOBVPseJU1EJPgm
"""

import logging
# from django.shortcuts import render
# from rest_framework.views import APIView
# from rest_framework import status
# from rest_framework.response import Response
# from django.db.models import F
# from home.serializers import RowDataSerializer, TemproryDataSerializer, ReportSerializer
# from home.models import RowData, TemproryData, Device, Product, Report, ProtectedPhoneNumber
# from rest_framework.decorators import api_view
# from rest_framework.response import Response
# # Create your views here.

# ایجاد یک logger ساده





from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from django.db.models import F
from home.serializers import RowDataSerializer, TemproryDataSerializer
from home.models import RowData, TemproryData, Device, Product, Report

logger = logging.getLogger(__name__)




class ReportMetadataView(APIView):

    def get(self, request):
        report_text = request.query_params.get('re')
        device_id = request.query_params.get('d')

        if device_id is None or report_text is None:
            return Response('Missing parameters', status=status.HTTP_400_BAD_REQUEST)

        # بررسی Device
        try:
            device_id = int(device_id)
            device = Device.objects.get(id=device_id)  # یا device_id=device_id
        except ValueError:
            return Response('device_id must be an integer', status=status.HTTP_400_BAD_REQUEST)
        except Device.DoesNotExist:
            return Response('Invalid device_id', status=status.HTTP_400_BAD_REQUEST)

        # ثبت گزارش
        report = Report.objects.create(report=report_text, device_id=device)

        return Response({
            'message': 'Report created successfully',
            'report_id': report.id
        }, status=status.HTTP_201_CREATED)









class GetMetadataView(APIView):

    def get(self, request):
        phone_number = request.query_params.get('ph')
        if not phone_number:
            return Response('phone_number is required', status=status.HTTP_400_BAD_REQUEST)

        try:
            record = TemproryData.objects.get(phone_number=phone_number)
            if record.gift_number == 0:
                return Response(status=status.HTTP_204_NO_CONTENT)
            else:
                return Response('OK', status=status.HTTP_200_OK)
        except TemproryData.DoesNotExist:
            return Response('OK', status=status.HTTP_200_OK)




class PostMetadataView(APIView):

    def get(self, request):
        gift_number = 2
        phone_number = request.query_params.get('ph')
        device_id = request.query_params.get('d')
        product_id = request.query_params.get('p')



        print(phone_number)
        print(device_id)
        print(product_id)

        if not phone_number:
            return Response('phone_number is required', status=status.HTTP_400_BAD_REQUEST)

        # ��� phone_number ����� ? ���� ���
        if device_id is None and product_id is None:
            try:
                record = TemproryData.objects.get(phone_number=phone_number)
                if record.gift_number == 0:
                    return Response(status=status.HTTP_204_NO_CONTENT)
                else:
                    return Response('OK', status=status.HTTP_200_OK)
            except TemproryData.DoesNotExist:
                return Response('OK', status=status.HTTP_200_OK)

        # phone_number + device_id + product_id ? ���� ���
        else:
            # ���������� device_id
            if device_id is not None:
                try:
                    device_id = int(device_id)
                    if not Device.objects.filter(device_id=device_id).exists():
                        return Response('Invalid device_id', status=status.HTTP_400_BAD_REQUEST)
                except ValueError:
                    return Response('device_id must be an integer', status=status.HTTP_400_BAD_REQUEST)

            # ���������� product_id
            if product_id is not None:
                try:
                    product_id = int(product_id)
                    if not Product.objects.filter(product_id=product_id).exists():
                        return Response('Invalid product_id', status=status.HTTP_400_BAD_REQUEST)
                except ValueError:
                    return Response('product_id must be an integer', status=status.HTTP_400_BAD_REQUEST)

            # ���� ���� RowData
            row_data = {
                'phone_number': phone_number,
                'device_id': device_id,
                'product_id': product_id,
            }
            serializer_row = RowDataSerializer(data=row_data)
            if not serializer_row.is_valid():
                print("test")
                return Response(serializer_row.errors, status=status.HTTP_400_BAD_REQUEST)
            serializer_row.save()

            # ���� TemproryData
            try:
                temp_record = TemproryData.objects.get(phone_number=phone_number)
                if temp_record.gift_number > 0:
                    temp_record.gift_number = F('gift_number') - 1
                    temp_record.save(update_fields=['gift_number'])
                    return Response('OK', status=status.HTTP_200_OK)
                else:
                    return Response('NOT', status=status.HTTP_204_NO_CONTENT)
            except TemproryData.DoesNotExist:
                temp_data = {
                    'phone_number': phone_number,
                    'gift_number': gift_number - 1,
                }
                serializer_temp = TemproryDataSerializer(data=temp_data)
                if serializer_temp.is_valid():
                    serializer_temp.save()
                    return Response('OK', status=status.HTTP_200_OK)
                else:
                    print("test 2")
                    return Response(serializer_temp.errors, status=status.HTTP_400_BAD_REQUEST)

