# FROM nginx:1.25.3
FROM docker.arvancloud.ir/nginx:1.27.4
# FROM docker.arvancloud.ir/nginx:1.25.3

COPY ./nginx-django-site/nginx-site-80.conf /etc/nginx/conf.d/default.conf

# EXPOSE 81

CMD ["nginx", "-g", "daemon off;"]
