# Generated by Django 5.2.1 on 2025-05-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربرها', 'verbose_name_plural': 'کاربرها'},
        ),
    ]
